# Google Cloud Build configuration for Beacon Studio
# Builds and deploys backend to Cloud Run

steps:
  # Build backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/beacon-backend/backend:$COMMIT_SHA'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/beacon-backend/backend:latest'
      - '-f'
      - 'backend/Dockerfile.beacon'
      - './backend'
    id: 'build-backend'

  # Push backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-docker.pkg.dev/$PROJECT_ID/beacon-backend/backend:$COMMIT_SHA'
    id: 'push-backend'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'beacon-backend'
      - '--image'
      - 'us-docker.pkg.dev/$PROJECT_ID/beacon-backend/backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '100'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,GOOGLE_REDIRECT_URI=https://shlinx.com/api/v1/auth/callback/google,GITHUB_REDIRECT_URI=https://shlinx.com/api/v1/auth/callback/github,GCS_BUCKET_NAME=$_GCS_BUCKET_NAME,GCS_PROJECT_ID=$PROJECT_ID,STRIPE_PRICE_ID_HASTE_I=$_STRIPE_PRICE_ID_HASTE_I,STRIPE_PRICE_ID_HASTE_II=$_STRIPE_PRICE_ID_HASTE_II,STRIPE_PRICE_ID_HASTE_III=$_STRIPE_PRICE_ID_HASTE_III'
      - '--set-secrets'
      - 'SECRET_KEY=beacon-secret-key:latest,DATABASE_URL=beacon-db-url:latest,GOOGLE_CLIENT_ID=beacon-google-client-id:latest,GOOGLE_CLIENT_SECRET=beacon-google-client-secret:latest,GITHUB_CLIENT_ID=beacon-github-client-id:latest,GITHUB_CLIENT_SECRET=beacon-github-client-secret:latest,STRIPE_API_KEY=beacon-stripe-api-key:latest,STRIPE_WEBHOOK_SECRET=beacon-stripe-webhook-secret:latest,GEMINI_API_KEY=beacon-gemini-api-key:latest'
      - '--service-account'
      - 'shlinx-cloud-run@webshareide.iam.gserviceaccount.com'
    id: 'deploy-backend'

images:
  - 'us-docker.pkg.dev/$PROJECT_ID/beacon-backend/backend:$COMMIT_SHA'
  - 'us-docker.pkg.dev/$PROJECT_ID/beacon-backend/backend:latest'

timeout: 1200s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

