steps:
  # Build frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/beacon-frontend/frontend:$COMMIT_SHA'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/beacon-frontend/frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    id: 'build-frontend'

  # Push frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-docker.pkg.dev/$PROJECT_ID/beacon-frontend/frontend:$COMMIT_SHA'
    id: 'push-frontend'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'beacon-frontend'
      - '--image'
      - 'us-docker.pkg.dev/$PROJECT_ID/beacon-frontend/frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60'
    id: 'deploy-frontend'

images:
  - 'us-docker.pkg.dev/$PROJECT_ID/beacon-frontend/frontend:$COMMIT_SHA'
  - 'us-docker.pkg.dev/$PROJECT_ID/beacon-frontend/frontend:latest'

timeout: 1200s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

